export let appleIpadProducts = [
  {
    id: "1",
    image: "../images/ipad/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2",
    image: "../images/ipad/1 (2).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "3",
    image: "../images/ipad/1 (3).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "4",
    image: "../images/ipad/1 (4).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "5",
    image: "../images/ipad/1 (5).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "6",
    image: "../images/ipad/1 (6).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "7",
    image: "../images/ipad/1 (7).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "8",
    image: "../images/ipad/1 (8).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "9",
    image: "../images/ipad/1 (9).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "10",
    image: "../images/ipad/1 (10).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "11",
    image: "../images/ipad/1 (11).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "12",
    image: "../images/ipad/1 (12).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "13",
    image: "../images/ipad/1 (13).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "14",
    image: "../images/ipad/1 (14).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "15",
    image: "../images/ipad/1 (15).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "16",
    image: "../images/ipad/1 (16).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "17",
    image: "../images/ipad/1 (17).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "18",
    image: "../images/ipad/1 (19).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "19",
    image: "../images/ipad/1 (20).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "20",
    image: "../images/ipad/1 (21).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "21",
    image: "../images/ipad/1 (22).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "22",
    image: "../images/ipad/1 (23).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "23",
    image: "../images/ipad/1 (24).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "24",
    image: "../images/ipad/1 (25).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "25",
    image: "../images/ipad/1 (26).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "26",
    image: "../images/ipad/1 (27).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "27",
    image: "../images/ipad/1 (28).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "28",
    image: "../images/ipad/1 (29).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "29",
    image: "../images/ipad/1 (30).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "30",
    image: "../images/ipad/1 (31).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "31",
    image: "../images/ipad/1 (32).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "32",
    image: "../images/ipad/1 (33).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "33",
    image: "../images/ipad/1 (34).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "34",
    image: "../images/ipad/1 (35).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "35",
    image: "../images/ipad/1 (36).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
];
