export let headPhonesProducts = [
  {
    id: "1",
    image: "../images/headPhones/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2",
    image: "../images/headPhones/1 (2).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "3",
    image: "../images/headPhones/1 (3).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "4",
    image: "../images/headPhones/1 (4).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "5",
    image: "../images/headPhones/1 (5).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "6",
    image: "../images/headPhones/1 (6).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "7",
    image: "../images/headPhones/1 (7).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "8",
    image: "../images/headPhones/1 (8).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "9",
    image: "../images/headPhones/1 (9).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "10",
    image: "../images/headPhones/1 (10).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "11",
    image: "../images/headPhones/1 (11).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "12",
    image: "../images/headPhones/1 (12).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "13",
    image: "../images/headPhones/1 (13).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
];
