export let laptopProducts = [
  {
    id: "1",
    image: "../images/laptop/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2",
    image: "../images/laptop/1 (2).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "3",
    image: "../images/laptop/1 (3).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "4",
    image: "../images/laptop/1 (4).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "5",
    image: "../images/laptop/1 (5).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "6",
    image: "../images/laptop/1 (6).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "7",
    image: "../images/laptop/1 (7).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "8",
    image: "../images/laptop/1 (8).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "13",
    image: "../images/laptop/1 (13).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "15",
    image: "../images/laptop/1 (15).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "16",
    image: "../images/laptop/1 (16).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "17",
    image: "../images/laptopApple/1 (17).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "18",
    image: "../images/laptopApple/1 (19).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "19",
    image: "../images/laptopApple/1 (20).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "20",
    image: "../images/laptopApple/1 (21).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "21",
    image: "../images/laptopApple/1 (22).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "22",
    image: "../images/laptopApple/1 (23).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "23",
    image: "../images/laptopApple/1 (24).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "24",
    image: "../images/laptopApple/1 (25).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "25",
    image: "../images/laptopApple/1 (26).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "26",
    image: "../images/laptopApple/1 (27).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "27",
    image: "../images/laptopApple/1 (28).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "28",
    image: "../images/laptopApple/1 (29).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
];
