export const products = [
  {
    id: "prds1",
    image: "images/mobile/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "prds2",
    image: "images/tablet/1 (1).jpg",
    name: "Tablet A2",
    color: "green",
    priceCents: "50000",
  },
  {
    id: "prds3",
    image: "images/shaatiyasha/1 (1).jpg",
    name: "T-shirt ",
    color: "green",
    priceCents: "2500",
  },
  {
    id: "prds4",
    image: "images/redmi/1 (1).jpg",
    name: "HP Levona",
    color: "green",
    priceCents: "60000",
  },
  {
    id: "prds5",
    image: "images/oppo/1 (1).jpg",
    name: "Pro 15",
    color: "green",
    priceCents: "1000",
  },

  {
    id: "prds6",
    image: "images/shaati/IMG-20221220-WA0131.jpg",
    name: "John",
    color: "green",
    priceCents: "1900",
  },
  {
    id: "prds7",
    image: "images/fanaanad/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "30000",
  },
  {
    id: "prds8",
    image: "images/samsung/1 (10).jpg",
    name: "John",
    color: "green",
    priceCents: "90000",
  },
  {
    id: "prds9",
    image: "images/headPhones/1 (10).jpg",
    name: "John",
    color: "green",
    priceCents: "70000",
  },
  {
    id: "prds10",
    image: "images/airpots/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "2000",
  },
  {
    id: "prds11",
    image: "images/laptop/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "1200",
  },
  {
    id: "prds12",
    image: "images/shaatiyasha/1 (2).jpg",
    name: "John",
    color: "green",
    priceCents: "2500",
  },
];
