const products = [
  {
    id: "1",
    image: "images/mobile/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "pageProduct",
  },
  {
    id: "2",
    image: "images/tablet/1 (1).jpg",
    name: "Tablet A2",
    color: "green",
    priceCents: "50000",
    category: "pageProduct",
  },
  {
    id: "3",
    image: "images/shaatiyasha/1 (1).jpg",
    name: "T-shirt ",
    color: "green",
    priceCents: "2500",
    category: "pageProduct",
  },
  {
    id: "4",
    image: "images/redmi/1 (1).jpg",
    name: "HP Levona",
    color: "green",
    priceCents: "60000",
    category: "pageProduct",
  },
  {
    id: "5",
    image: "images/oppo/1 (1).jpg",
    name: "Pro 15",
    color: "green",
    priceCents: "1000",
    category: "pageProduct",
  },

  {
    id: "6",
    image: "images/shaati/IMG-20221220-WA0131.jpg",
    name: "John",
    color: "green",
    priceCents: "1900",
    category: "pageProduct",
  },
  {
    id: "7",
    image: "images/fanaanad/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "30000",
    category: "pageProduct",
  },
  {
    id: "8",
    image: "images/samsung/1 (10).jpg",
    name: "John",
    color: "green",
    priceCents: "90000",
    category: "pageProduct",
  },
  {
    id: "9",
    image: "images/headPhones/1 (10).jpg",
    name: "John",
    color: "green",
    priceCents: "70000",
    category: "pageProduct",
  },
  {
    id: "10",
    image: "images/airpots/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "2000",
    category: "pageProduct",
  },
  {
    id: "11",
    image: "images/laptop/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "1200",
    category: "pageProduct",
  },
  {
    id: "12",
    image: "images/shaatiyasha/1 (2).jpg",
    name: "John",
    color: "green",
    priceCents: "2500",
    category: "pageProduct",
  },
];
let mobileIphones = [
  {
    id: "1",
    image: "../images/iphones/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "2",
    image: "../images/iphones/1 (2).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "3",
    image: "../images/iphones/1 (3).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "4",
    image: "../images/iphones/1 (4).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "5",
    image: "../images/iphones/1 (5).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "6",
    image: "../images/iphones/1 (6).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "7",
    image: "../images/iphones/1 (7).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "8",
    image: "../images/iphones/1 (8).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "9",
    image: "../images/iphones/1 (9).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "10",
    image: "../images/iphones/1 (10).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "11",
    image: "../images/iphones/1 (11).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "12",
    image: "../images/iphones/1 (12).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "13",
    image: "../images/iphones/1 (13).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "14",
    image: "../images/iphones/1 (14).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "15",
    image: "../images/iphones/1 (15).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "16",
    image: "../images/iphones/1 (16).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "17",
    image: "../images/iphones/1 (17).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "18",
    image: "../images/iphones/1 (19).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "19",
    image: "../images/iphones/1 (20).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "20",
    image: "../images/iphones/1 (21).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "21",
    image: "../images/iphones/1 (22).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "22",
    image: "../images/iphones/1 (23).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "23",
    image: "../images/iphones/1 (24).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "24",
    image: "../images/iphones/1 (25).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "25",
    image: "../images/iphones/1 (26).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "26",
    image: "../images/iphones/1 (27).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "27",
    image: "../images/iphones/1 (28).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "28",
    image: "../images/iphones/1 (29).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "29",
    image: "../images/iphones/1 (30).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "30",
    image: "../images/iphones/1 (31).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "31",
    image: "../images/iphones/1 (32).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "32",
    image: "../images/iphones/1 (33).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "33",
    image: "../images/iphones/1 (34).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "34",
    image: "../images/iphones/1 (35).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "35",
    image: "../images/iphones/1 (36).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
  {
    id: "36",
    image: "../images/iphones/last.jpeg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
    category: "Iphone",
  },
];

const categories = {
  pageProduct: [],
  Iphone: [],
};

products.map((product) => {
  const categoryKey = product.category;
  if (categories[categoryKey]) {
    categories[categoryKey].push(product);
  }
});

const pageProduct = categories.pageProduct;
const Iphone = categories.Iphone;

console.log("pageProduct:", pageProduct);
console.log("iphones:", Iphone);
