export let airpodsProducts = [
  {
    id: "airPods1",
    image: "../images/airpots/1 (1).jpg",
    name: "AirPods",
    color: "green",
    category: "phones",
    priceCents: "129900",
  },
  {
    id: "airPods2",
    image: "../images/airpots/1 (2).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods3",
    image: "../images/airpots/1 (3).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods4",
    image: "../images/airpots/1 (4).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods5",
    image: "../images/airpots/1 (5).jpg",
    name: "AirPods",
    color: "green",
    category: "phones",
    priceCents: "129900",
  },
  {
    id: "airPods6",
    image: "../images/airpots/1 (6).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods7",
    image: "../images/airpots/1 (7).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods8",
    image: "../images/airpots/1 (8).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods9",
    image: "../images/headPhones/1 (9).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods10",
    image: "../images/headPhones/1 (10).jpg",
    name: "AirPods",
    color: "green",
    category: "phones",
    priceCents: "129900",
  },
  {
    id: "airPods11",
    image: "../images/headPhones/1 (11).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods12",
    image: "../images/headPhones/1 (12).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods13",
    image: "../images/headPhones/1 (13).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
];

export let appleLaptopProducts = [
  {
    id: "apple1",
    image: "../images/laptopApple/1 (1).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple2",
    image: "../images/laptopApple/1 (2).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple3",
    image: "../images/laptopApple/1 (3).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple4",
    image: "../images/laptopApple/1 (4).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple5",
    image: "../images/laptopApple/1 (5).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple6",
    image: "../images/laptopApple/1 (6).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple7",
    image: "../images/laptopApple/1 (7).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple8",
    image: "../images/laptopApple/1 (8).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple9",
    image: "../images/laptopApple/1 (9).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple10",
    image: "../images/laptopApple/1 (10).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple11",
    image: "../images/laptopApple/1 (11).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple12",
    image: "../images/laptopApple/1 (12).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple13",
    image: "../images/laptopApple/1 (13).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple14",
    image: "../images/laptopApple/1 (14).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple15",
    image: "../images/laptopApple/1 (15).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple16",
    image: "../images/laptopApple/1 (16).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple17",
    image: "../images/laptopApple/1 (17).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple18",
    image: "../images/laptopApple/1 (19).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple19",
    image: "../images/laptopApple/1 (20).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple20",
    image: "../images/laptopApple/1 (21).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple21",
    image: "../images/laptopApple/1 (22).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
];
export let fanaanadProducts = [
  {
    id: "fanaanad1",
    image: "../images/fanaanad/1 (1).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad2",
    image: "../images/fanaanad/1 (2).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad3",
    image: "../images/fanaanad/1 (3).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad4",
    image: "../images/fanaanad/1 (4).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad5",
    image: "../images/fanaanad/1 (5).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad6",
    image: "../images/fanaanad/1 (6).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad7",
    image: "../images/fanaanad/1 (7).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad8",
    image: "../images/fanaanad/1 (8).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad9",
    image: "../images/fanaanad/1 (9).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad10",
    image: "../images/fanaanad/1 (10).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad11",
    image: "../images/fanaanad/1 (11).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad12",
    image: "../images/fanaanad/1 (12).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad13",
    image: "../images/fanaanad/1 (13).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad14",
    image: "../images/fanaanad/1 (14).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad15",
    image: "../images/fanaanad/1 (15).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad16",
    image: "../images/fanaanad/1 (16).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad17",
    image: "../images/fanaanad/1 (17).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad18",
    image: "../images/fanaanad/1 (19).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad19",
    image: "../images/fanaanad/1 (20).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad20",
    image: "../images/fanaanad/1 (21).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad21",
    image: "../images/fanaanad/1 (22).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad22",
    image: "../images/fanaanad/1 (23).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad23",
    image: "../images/fanaanad/1 (24).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad24",
    image: "../images/fanaanad/1 (25).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad25",
    image: "../images/fanaanad/1 (26).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad26",
    image: "../images/fanaanad/1 (27).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad27",
    image: "../images/fanaanad/1 (28).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
];
export let headPhonesProducts = [
  {
    id: "headPhones1",
    image: "../images/headPhones/1 (1).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones2",
    image: "../images/headPhones/1 (2).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones3",
    image: "../images/headPhones/1 (3).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones4",
    image: "../images/headPhones/1 (4).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones5",
    image: "../images/headPhones/1 (5).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones6",
    image: "../images/headPhones/1 (6).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones7",
    image: "../images/headPhones/1 (7).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones8",
    image: "../images/headPhones/1 (8).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones9",
    image: "../images/headPhones/1 (9).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones10",
    image: "../images/headPhones/1 (10).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones11",
    image: "../images/headPhones/1 (11).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones12",
    image: "../images/headPhones/1 (12).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones13",
    image: "../images/headPhones/1 (13).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
];

export let laptopProducts = [
  {
    id: "laptop1",
    image: "../images/laptop/1 (1).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop2",
    image: "../images/laptop/1 (2).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop3",
    image: "../images/laptop/1 (3).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop4",
    image: "../images/laptop/1 (4).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop5",
    image: "../images/laptop/1 (5).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop6",
    image: "../images/laptop/1 (6).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop7",
    image: "../images/laptop/1 (7).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop8",
    image: "../images/laptop/1 (8).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop13",
    image: "../images/laptop/1 (13).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop15",
    image: "../images/laptop/1 (15).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop16",
    image: "../images/laptop/1 (16).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop17",
    image: "../images/laptopApple/1 (17).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop18",
    image: "../images/laptopApple/1 (19).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop19",
    image: "../images/laptopApple/1 (20).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop20",
    image: "../images/laptopApple/1 (21).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop21",
    image: "../images/laptopApple/1 (22).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop22",
    image: "../images/laptopApple/1 (23).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop23",
    image: "../images/laptopApple/1 (24).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop24",
    image: "../images/laptopApple/1 (25).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop25",
    image: "../images/laptopApple/1 (26).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop26",
    image: "../images/laptopApple/1 (27).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop27",
    image: "../images/laptopApple/1 (28).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop28",
    image: "../images/laptopApple/1 (29).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
];

export const products = [
  {
    id: "prds1",
    image: "images/mobile/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "prds2",
    image: "images/tablet/1 (1).jpg",
    name: "Tablet A2",
    color: "green",
    priceCents: "50000",
  },
  {
    id: "prds3",
    image: "images/shaatiyasha/1 (1).jpg",
    name: "T-shirt ",
    color: "green",
    priceCents: "2500",
  },
  {
    id: "prds4",
    image: "images/redmi/1 (1).jpg",
    name: "HP Levona",
    color: "green",
    priceCents: "60000",
  },
  {
    id: "prds5",
    image: "images/oppo/1 (1).jpg",
    name: "Pro 15",
    color: "green",
    priceCents: "1000",
  },

  {
    id: "prds6",
    image: "images/shaati/IMG-20221220-WA0131.jpg",
    name: "John",
    color: "green",
    priceCents: "1900",
  },
  {
    id: "prds7",
    image: "images/fanaanad/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "30000",
  },
  {
    id: "prds8",
    image: "images/samsung/1 (10).jpg",
    name: "John",
    color: "green",
    priceCents: "90000",
  },
  {
    id: "prds9",
    image: "images/headPhones/1 (10).jpg",
    name: "John",
    color: "green",
    priceCents: "70000",
  },
  {
    id: "prds10",
    image: "images/airpots/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "2000",
  },
  {
    id: "prds11",
    image: "images/laptop/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "1200",
  },
  {
    id: "prds12",
    image: "images/shaatiyasha/1 (2).jpg",
    name: "John",
    color: "green",
    priceCents: "2500",
  },
];

export const productSomOnlne = [
  {
    id: "1",
    image: "images/mobile/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2",
    name: "Tablet A2",
    image: "images/tablet/1 (1).jpg",
    color: "green",
    priceCents: "50000",
  },
  {
    id: "3",
    name: "T-shirt ",
    image: "images/shaatiyasha/1 (1).jpg",
    color: "green",
    priceCents: "2500",
  },
  {
    id: "4",
    name: "HP Levona",
    image: "images/redmi/1 (1).jpg",
    color: "green",
    priceCents: "60000",
  },
  {
    id: "5",
    name: "Pro 15",
    image: "images/oppo/1 (1).jpg",
    color: "green",
    priceCents: "1000",
  },

  {
    id: "6",
    name: "John",
    image: "images/shaati/IMG-20221220-WA0131.jpg",
    color: "green",
    priceCents: "1900",
  },
  {
    id: "7",
    name: "John",
    image: "images/fanaanad/1 (1).jpg",
    color: "green",
    priceCents: "30000",
  },
  {
    id: "8",
    name: "John",
    image: "images/samsung/1 (10).jpg",
    color: "green",
    priceCents: "90000",
  },
  {
    id: "9",
    name: "John",
    image: "images/headPhones/1 (10).jpg",
    color: "green",
    priceCents: "70000",
  },
  {
    id: "10",
    name: "John",
    image: "images/airpots/1 (1).jpg",
    color: "green",
    priceCents: "2000",
  },
  {
    id: "11",
    name: "John",
    image: "images/laptop/1 (1).jpg",
    color: "green",
    priceCents: "1200",
  },
  {
    id: "12",
    name: "John",
    image: "images/shaatiyasha/1 (2).jpg",
    color: "green",
    priceCents: "2500",
  },
];

export let shaatiProducts = [
  {
    id: "shaati1",
    image: "../images/shaatiyasha/1 (1).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati2",
    image: "../images/shaatiyasha/1 (2).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati3",
    image: "../images/shaatiyasha/1 (3).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati4",
    image: "../images/shaatiyasha/1 (4).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati5",
    image: "../images/shaatiyasha/1 (5).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati6",
    image: "../images/shaatiyasha/1 (6).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati7",
    image: "../images/shaatiyasha/1 (7).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati8",
    image: "../images/shaatiyasha/1 (8).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati9",
    image: "../images/shaatiyasha/1 (9).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati10",
    image: "../images/shaatiyasha/1 (10).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati11",
    image: "../images/shaatiyasha/1 (11).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati12",
    image: "../images/shaatiyasha/1 (12).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati13",
    image: "../images/shaatiyasha/1 (13).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati14",
    image: "../images/shaatiyasha/1 (14).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati15",
    image: "../images/shaatiyasha/1 (15).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati16",
    image: "../images/shaatiyasha/1 (16).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati17",
    image: "../images/shaatiyasha/1 (17).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati18",
    image: "../images/shaatiyasha/1 (19).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati19",
    image: "../images/shaatiyasha/1 (20).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati20",
    image: "../images/shaatiyasha/1 (21).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati21",
    image: "../images/shaatiyasha/1 (22).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati22",
    image: "../images/shaatiyasha/1 (23).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati23",
    image: "../images/shaatiyasha/1 (24).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati24",
    image: "../images/shaatiyasha/1 (25).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati25",
    image: "../images/shaatiyasha/1 (26).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati26",
    image: "../images/shaatiyasha/1 (27).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati27",
    image: "../images/shaatiyasha/1 (28).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati28",
    image: "../images/shaatiyasha/1 (29).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati29",
    image: "../images/shaatiyasha/1 (30).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati30",
    image: "../images/shaatiyasha/1 (31).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati31",
    image: "../images/shaatiyasha/1 (32).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati32",
    image: "../images/shaatiyasha/1 (33).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati33",
    image: "../images/shaatiyasha/1 (34).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati34",
    image: "../images/shaatiyasha/1 (35).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati35",
    image: "../images/shaatiyasha/1 (36).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati36",
    image: "../images/shaatiyasha/1 (3).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
];

export let shortAirpodsProducts = [
  {
    id: "shortAirpods1",
    image: "../images/airpots/1 (1).jpg",
    name: "ShortAirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods2",
    image: "../images/airpots/1 (2).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods3",
    image: "../images/airpots/1 (3).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods4",
    image: "../images/airpots/1 (4).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods5",
    image: "../images/airpots/1 (5).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods6",
    image: "../images/airpots/1 (6).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods7",
    image: "../images/airpots/1 (7).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods8",
    image: "../images/airpots/1 (8).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods9",
    image: "../images/airpots/1 (9).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods10",
    image: "../images/airpots/1 (10).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods11",
    image: "../images/airpots/1 (11).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods12",
    image: "../images/airpots/1 (12).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods13",
    image: "../images/airpots/1 (13).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods14",
    image: "../images/airpots/1 (14).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (15).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (16).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (17).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (18).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (19).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
];

export let tshirtPrdoct = [
  {
    id: "tShirt1",
    image: "../images/fanaanad/1 (1).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt2",
    image: "../images/fanaanad/1 (2).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt3",
    image: "../images/fanaanad/1 (3).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt4",
    image: "../images/fanaanad/1 (4).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt5",
    image: "../images/fanaanad/1 (5).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt6",
    image: "../images/fanaanad/1 (6).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt7",
    image: "../images/fanaanad/1 (7).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt8",
    image: "../images/fanaanad/1 (8).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt9",
    image: "../images/fanaanad/1 (9).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt10",
    image: "../images/fanaanad/1 (10).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt11",
    image: "../images/fanaanad/1 (11).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt12",
    image: "../images/fanaanad/1 (12).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt13",
    image: "../images/fanaanad/1 (13).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt14",
    image: "../images/fanaanad/1 (14).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt15",
    image: "../images/fanaanad/1 (15).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt16",
    image: "../images/fanaanad/1 (16).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt17",
    image: "../images/shaatiyasha/1 (17).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt18",
    image: "../images/shaatiyasha/1 (19).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt19",
    image: "../images/shaatiyasha/1 (20).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt20",
    image: "../images/shaatiyasha/1 (21).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt21",
    image: "../images/shaatiyasha/1 (22).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt22",
    image: "../images/shaatiyasha/1 (23).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt23",
    image: "../images/shaatiyasha/1 (24).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt24",
    image: "../images/shaatiyasha/1 (25).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt25",
    image: "../images/shaatiyasha/1 (26).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt26",
    image: "../images/shaatiyasha/1 (27).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt27",
    image: "../images/shaatiyasha/1 (28).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt28",
    image: "../images/shaatiyasha/1 (29).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt29",
    image: "../images/shaatiyasha/1 (30).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt30",
    image: "../images/shaatiyasha/1 (31).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt31",
    image: "../images/shaatiyasha/1 (32).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt32",
    image: "../images/shaatiyasha/1 (33).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt33",
    image: "../images/shaatiyasha/1 (34).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt34",
    image: "../images/shaatiyasha/1 (35).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt35",
    image: "../images/shaatiyasha/1 (36).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
];
