export let airpodsProducts = [
  {
    id: "airPods1",
    image: "../images/airpots/1 (1).jpg",
    name: "AirPods",
    color: "green",
    category: "phones",
    priceCents: "129900",
  },
  {
    id: "airPods2",
    image: "../images/airpots/1 (2).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods3",
    image: "../images/airpots/1 (3).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods4",
    image: "../images/airpots/1 (4).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods5",
    image: "../images/airpots/1 (5).jpg",
    name: "AirPods",
    color: "green",
    category: "phones",
    priceCents: "129900",
  },
  {
    id: "airPods6",
    image: "../images/airpots/1 (6).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods7",
    image: "../images/airpots/1 (7).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods8",
    image: "../images/airpots/1 (8).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods9",
    image: "../images/headPhones/1 (9).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods10",
    image: "../images/headPhones/1 (10).jpg",
    name: "AirPods",
    color: "green",
    category: "phones",
    priceCents: "129900",
  },
  {
    id: "airPods11",
    image: "../images/headPhones/1 (11).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods12",
    image: "../images/headPhones/1 (12).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "airPods13",
    image: "../images/headPhones/1 (13).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
];
export let appleIpadProducts = [
  {
    id: "appleIpad1",
    image: "../images/ipad/1 (1).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad2",
    image: "../images/ipad/1 (2).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad3",
    image: "../images/ipad/1 (3).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad4",
    image: "../images/ipad/1 (4).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad5",
    image: "../images/ipad/1 (5).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad6",
    image: "../images/ipad/1 (6).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad7",
    image: "../images/ipad/1 (7).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad8",
    image: "../images/ipad/1 (8).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad9",
    image: "../images/ipad/1 (9).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad10",
    image: "../images/ipad/1 (10).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad11",
    image: "../images/ipad/1 (11).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad12",
    image: "../images/ipad/1 (12).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad13",
    image: "../images/ipad/1 (13).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad14",
    image: "../images/ipad/1 (14).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad15",
    image: "../images/ipad/1 (15).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad16",
    image: "../images/ipad/1 (16).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad17",
    image: "../images/ipad/1 (17).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad18",
    image: "../images/ipad/1 (19).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad19",
    image: "../images/ipad/1 (20).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad20",
    image: "../images/ipad/1 (21).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad21",
    image: "../images/ipad/1 (22).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad22",
    image: "../images/ipad/1 (23).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad23",
    image: "../images/ipad/1 (24).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad24",
    image: "../images/ipad/1 (25).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad25",
    image: "../images/ipad/1 (26).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad26",
    image: "../images/ipad/1 (27).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad27",
    image: "../images/ipad/1 (28).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad28",
    image: "../images/ipad/1 (29).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad29",
    image: "../images/ipad/1 (30).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad30",
    image: "../images/ipad/1 (31).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad31",
    image: "../images/ipad/1 (32).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad32",
    image: "../images/ipad/1 (33).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad33",
    image: "../images/ipad/1 (34).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad34",
    image: "../images/ipad/1 (35).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "appleIpad35",
    image: "../images/ipad/1 (36).jpg",
    name: "Apple Ipad",
    color: "green",
    priceCents: "129900",
  },
];

export let appleLaptopProducts = [
  {
    id: "apple1",
    image: "../images/laptopApple/1 (1).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple2",
    image: "../images/laptopApple/1 (2).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple3",
    image: "../images/laptopApple/1 (3).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple4",
    image: "../images/laptopApple/1 (4).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple5",
    image: "../images/laptopApple/1 (5).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple6",
    image: "../images/laptopApple/1 (6).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple7",
    image: "../images/laptopApple/1 (7).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple8",
    image: "../images/laptopApple/1 (8).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple9",
    image: "../images/laptopApple/1 (9).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple10",
    image: "../images/laptopApple/1 (10).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple11",
    image: "../images/laptopApple/1 (11).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple12",
    image: "../images/laptopApple/1 (12).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple13",
    image: "../images/laptopApple/1 (13).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple14",
    image: "../images/laptopApple/1 (14).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple15",
    image: "../images/laptopApple/1 (15).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple16",
    image: "../images/laptopApple/1 (16).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple17",
    image: "../images/laptopApple/1 (17).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple18",
    image: "../images/laptopApple/1 (19).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple19",
    image: "../images/laptopApple/1 (20).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple20",
    image: "../images/laptopApple/1 (21).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "apple21",
    image: "../images/laptopApple/1 (22).jpg",
    name: "Apple Laptop",
    color: "green",
    priceCents: "129900",
  },
];
export let fanaanadProducts = [
  {
    id: "fanaanad1",
    image: "../images/fanaanad/1 (1).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad2",
    image: "../images/fanaanad/1 (2).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad3",
    image: "../images/fanaanad/1 (3).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad4",
    image: "../images/fanaanad/1 (4).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad5",
    image: "../images/fanaanad/1 (5).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad6",
    image: "../images/fanaanad/1 (6).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad7",
    image: "../images/fanaanad/1 (7).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad8",
    image: "../images/fanaanad/1 (8).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad9",
    image: "../images/fanaanad/1 (9).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad10",
    image: "../images/fanaanad/1 (10).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad11",
    image: "../images/fanaanad/1 (11).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad12",
    image: "../images/fanaanad/1 (12).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad13",
    image: "../images/fanaanad/1 (13).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad14",
    image: "../images/fanaanad/1 (14).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad15",
    image: "../images/fanaanad/1 (15).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad16",
    image: "../images/fanaanad/1 (16).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad17",
    image: "../images/fanaanad/1 (17).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad18",
    image: "../images/fanaanad/1 (19).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad19",
    image: "../images/fanaanad/1 (20).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad20",
    image: "../images/fanaanad/1 (21).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad21",
    image: "../images/fanaanad/1 (22).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad22",
    image: "../images/fanaanad/1 (23).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad23",
    image: "../images/fanaanad/1 (24).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad24",
    image: "../images/fanaanad/1 (25).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad25",
    image: "../images/fanaanad/1 (26).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad26",
    image: "../images/fanaanad/1 (27).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "fanaanad27",
    image: "../images/fanaanad/1 (28).jpg",
    name: "Fanaanad",
    color: "green",
    priceCents: "129900",
  },
];
export let headPhonesProducts = [
  {
    id: "headPhones1",
    image: "../images/headPhones/1 (1).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones2",
    image: "../images/headPhones/1 (2).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones3",
    image: "../images/headPhones/1 (3).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones4",
    image: "../images/headPhones/1 (4).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones5",
    image: "../images/headPhones/1 (5).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones6",
    image: "../images/headPhones/1 (6).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones7",
    image: "../images/headPhones/1 (7).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones8",
    image: "../images/headPhones/1 (8).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones9",
    image: "../images/headPhones/1 (9).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones10",
    image: "../images/headPhones/1 (10).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones11",
    image: "../images/headPhones/1 (11).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones12",
    image: "../images/headPhones/1 (12).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "headPhones13",
    image: "../images/headPhones/1 (13).jpg",
    name: "HeadPhones",
    color: "green",
    priceCents: "129900",
  },
];
export let hpLaptopProducts = [
  {
    id: "hpLaptop1",
    image: "../images/laptop/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop2",
    image: "../images/laptop/1 (2).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop3",
    image: "../images/laptop/1 (3).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop4",
    image: "../images/laptop/1 (4).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop5",
    image: "../images/laptop/1 (5).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop6",
    image: "../images/laptop/1 (6).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop7",
    image: "../images/laptop/1 (7).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop8",
    image: "../images/laptop/1 (8).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },

  {
    id: "hpLaptop13",
    image: "../images/laptop/1 (13).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },

  {
    id: "hpLaptop15",
    image: "../images/laptop/1 (15).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop16",
    image: "../images/laptop/1 (16).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop17",
    image: "../images/laptop/1 (17).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop18",
    image: "../images/laptop/1 (19).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop19",
    image: "../images/laptop/1 (20).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop20",
    image: "../images/laptop/1 (21).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop21",
    image: "../images/laptop/1 (22).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop22",
    image: "../images/laptop/1 (23).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop23",
    image: "../images/laptop/1 (24).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop24",
    image: "../images/laptop/1 (25).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop25",
    image: "../images/laptop/1 (26).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop26",
    image: "../images/laptop/1 (27).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop27",
    image: "../images/laptop/1 (28).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop28",
    image: "../images/laptop/1 (29).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop29",
    image: "../images/laptop/1 (30).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop30",
    image: "../images/laptop/1 (31).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop31",
    image: "../images/laptop/1 (32).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "hpLaptop32",
    image: "../images/laptop/1 (33).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
];
export let huaweiProducts = [
  {
    id: "huawei1",
    image: "../images/huawei/1 (1).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei2",
    image: "../images/huawei/1 (2).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei3",
    image: "../images/huawei/1 (3).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei4",
    image: "../images/huawei/1 (4).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei5",
    image: "../images/huawei/1 (5).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei6",
    image: "../images/huawei/1 (6).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei7",
    image: "../images/huawei/1 (7).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei8",
    image: "../images/huawei/1 (8).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei9",
    image: "../images/huawei/1 (9).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei10",
    image: "../images/huawei/1 (10).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei11",
    image: "../images/huawei/1 (11).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei12",
    image: "../images/huawei/1 (12).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei13",
    image: "../images/huawei/1 (13).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei14",
    image: "../images/huawei/1 (14).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei15",
    image: "../images/huawei/1 (15).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei16",
    image: "../images/huawei/1 (16).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei17",
    image: "../images/huawei/1 (17).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei18",
    image: "../images/huawei/1 (19).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei19",
    image: "../images/huawei/1 (20).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei20",
    image: "../images/huawei/1 (21).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei21",
    image: "../images/huawei/1 (22).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei22",
    image: "../images/huawei/1 (23).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "huawei23",
    image: "../images/huawei/1 (24).jpg",
    name: "Huawei",
    color: "green",
    priceCents: "129900",
  },
];

export let mobileIphones = [
  {
    id: "124ds21",
    image: "../images/iphones/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds22",
    image: "../images/iphones/1 (2).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds23",
    image: "../images/iphones/1 (3).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds24",
    image: "../images/iphones/1 (4).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds25",
    image: "../images/iphones/1 (5).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds26",
    image: "../images/iphones/1 (6).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds27",
    image: "../images/iphones/1 (7).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds28",
    image: "../images/iphones/1 (8).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds29",
    image: "../images/iphones/1 (9).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds210",
    image: "../images/iphones/1 (10).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds211",
    image: "../images/iphones/1 (11).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds212",
    image: "../images/iphones/1 (12).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds213",
    image: "../images/iphones/1 (13).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds214",
    image: "../images/iphones/1 (14).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds215",
    image: "../images/iphones/1 (15).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds216",
    image: "../images/iphones/1 (16).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds217",
    image: "../images/iphones/1 (17).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds218",
    image: "../images/iphones/1 (19).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds219",
    image: "../images/iphones/1 (20).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds220",
    image: "../images/iphones/1 (21).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds221",
    image: "../images/iphones/1 (22).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds222",
    image: "../images/iphones/1 (23).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds223",
    image: "../images/iphones/1 (24).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds224",
    image: "../images/iphones/1 (25).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds225",
    image: "../images/iphones/1 (26).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds226",
    image: "../images/iphones/1 (27).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds227",
    image: "../images/iphones/1 (28).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds228",
    image: "../images/iphones/1 (29).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds229",
    image: "../images/iphones/1 (30).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds230",
    image: "../images/iphones/1 (31).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds231",
    image: "../images/iphones/1 (32).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds232",
    image: "../images/iphones/1 (33).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds233",
    image: "../images/iphones/1 (34).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds234",
    image: "../images/iphones/1 (35).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds235",
    image: "../images/iphones/1 (36).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "124ds236",
    image: "../images/iphones/last.jpeg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
];

export let laptopProducts = [
  {
    id: "laptop1",
    image: "../images/laptop/1 (1).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop2",
    image: "../images/laptop/1 (2).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop3",
    image: "../images/laptop/1 (3).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop4",
    image: "../images/laptop/1 (4).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop5",
    image: "../images/laptop/1 (5).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop6",
    image: "../images/laptop/1 (6).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop7",
    image: "../images/laptop/1 (7).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop8",
    image: "../images/laptop/1 (8).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop13",
    image: "../images/laptop/1 (13).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop15",
    image: "../images/laptop/1 (15).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop16",
    image: "../images/laptop/1 (16).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop17",
    image: "../images/laptopApple/1 (17).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop18",
    image: "../images/laptopApple/1 (19).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop19",
    image: "../images/laptopApple/1 (20).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop20",
    image: "../images/laptopApple/1 (21).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop21",
    image: "../images/laptopApple/1 (22).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop22",
    image: "../images/laptopApple/1 (23).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop23",
    image: "../images/laptopApple/1 (24).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop24",
    image: "../images/laptopApple/1 (25).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop25",
    image: "../images/laptopApple/1 (26).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop26",
    image: "../images/laptopApple/1 (27).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop27",
    image: "../images/laptopApple/1 (28).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "laptop28",
    image: "../images/laptopApple/1 (29).jpg",
    name: "Laptop",
    color: "green",
    priceCents: "129900",
  },
];
export let mobile = [
  {
    id: "2461iph1",
    image: "../images/mobile/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph2",
    image: "../images/mobile/1 (2).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph3",
    image: "../images/mobile/1 (3).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph4",
    image: "../images/mobile/1 (4).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph5",
    image: "../images/mobile/1 (5).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph6",
    image: "../images/mobile/1 (6).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph7",
    image: "../images/mobile/1 (7).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph8",
    image: "../images/mobile/1 (8).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph9",
    image: "../images/mobile/1 (9).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph10",
    image: "../images/mobile/1 (10).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph11",
    image: "../images/mobile/1 (11).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph12",
    image: "../images/mobile/1 (12).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph13",
    image: "../images/mobile/1 (13).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph14",
    image: "../images/mobile/1 (14).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph15",
    image: "../images/mobile/1 (15).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph16",
    image: "../images/mobile/1 (16).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph17",
    image: "../images/mobile/1 (17).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph18",
    image: "../images/mobile/1 (19).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph19",
    image: "../images/mobile/1 (20).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph20",
    image: "../images/mobile/1 (21).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph21",
    image: "../images/mobile/1 (22).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph22",
    image: "../images/mobile/1 (23).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph23",
    image: "../images/mobile/1 (24).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph24",
    image: "../images/mobile/1 (25).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph25",
    image: "../images/mobile/1 (26).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph26",
    image: "../images/mobile/1 (27).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph27",
    image: "../images/mobile/1 (28).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph28",
    image: "../images/mobile/1 (29).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph29",
    image: "../images/mobile/1 (30).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph30",
    image: "../images/mobile/1 (31).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph31",
    image: "../images/mobile/1 (32).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph32",
    image: "../images/mobile/1 (33).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2461iph33",
    image: "../images/mobile/1 (34).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },

  {
    id: "2461iph34",
    image: "../images/mobile/1 (1).jpeg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
];
export let oppoProducts = [
  {
    id: "oppo1",
    image: "../images/oppo/1 (1).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo2",
    image: "../images/oppo/1 (2).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo3",
    image: "../images/oppo/1 (3).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo4",
    image: "../images/oppo/1 (4).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo5",
    image: "../images/oppo/1 (5).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo6",
    image: "../images/oppo/1 (6).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo7",
    image: "../images/oppo/1 (7).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo8",
    image: "../images/oppo/1 (8).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo9",
    image: "../images/oppo/1 (9).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo10",
    image: "../images/oppo/1 (10).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo11",
    image: "../images/oppo/1 (11).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo12",
    image: "../images/oppo/1 (12).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo13",
    image: "../images/oppo/1 (13).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo14",
    image: "../images/oppo/1 (14).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo15",
    image: "../images/oppo/1 (15).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo16",
    image: "../images/oppo/1 (16).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo17",
    image: "../images/oppo/1 (17).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "oppo18",
    image: "../images/oppo/1 (19).jpg",
    name: "Oppo",
    color: "green",
    priceCents: "129900",
  },
];
export const products = [
  {
    id: "prds1",
    image: "images/mobile/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "prds2",
    image: "images/tablet/1 (1).jpg",
    name: "Tablet A2",
    color: "green",
    priceCents: "50000",
  },
  {
    id: "prds3",
    image: "images/shaatiyasha/1 (1).jpg",
    name: "T-shirt ",
    color: "green",
    priceCents: "2500",
  },
  {
    id: "prds4",
    image: "images/redmi/1 (1).jpg",
    name: "HP Levona",
    color: "green",
    priceCents: "60000",
  },
  {
    id: "prds5",
    image: "images/oppo/1 (1).jpg",
    name: "Pro 15",
    color: "green",
    priceCents: "1000",
  },

  {
    id: "prds6",
    image: "images/shaati/IMG-20221220-WA0131.jpg",
    name: "John",
    color: "green",
    priceCents: "1900",
  },
  {
    id: "prds7",
    image: "images/fanaanad/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "30000",
  },
  {
    id: "prds8",
    image: "images/samsung/1 (10).jpg",
    name: "John",
    color: "green",
    priceCents: "90000",
  },
  {
    id: "prds9",
    image: "images/headPhones/1 (10).jpg",
    name: "John",
    color: "green",
    priceCents: "70000",
  },
  {
    id: "prds10",
    image: "images/airpots/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "2000",
  },
  {
    id: "prds11",
    image: "images/laptop/1 (1).jpg",
    name: "John",
    color: "green",
    priceCents: "1200",
  },
  {
    id: "prds12",
    image: "images/shaatiyasha/1 (2).jpg",
    name: "John",
    color: "green",
    priceCents: "2500",
  },
];

export const productSomOnlne = [
  {
    id: "1",
    image: "images/mobile/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2",
    name: "Tablet A2",
    image: "images/tablet/1 (1).jpg",
    color: "green",
    priceCents: "50000",
  },
  {
    id: "3",
    name: "T-shirt ",
    image: "images/shaatiyasha/1 (1).jpg",
    color: "green",
    priceCents: "2500",
  },
  {
    id: "4",
    name: "HP Levona",
    image: "images/redmi/1 (1).jpg",
    color: "green",
    priceCents: "60000",
  },
  {
    id: "5",
    name: "Pro 15",
    image: "images/oppo/1 (1).jpg",
    color: "green",
    priceCents: "1000",
  },

  {
    id: "6",
    name: "John",
    image: "images/shaati/IMG-20221220-WA0131.jpg",
    color: "green",
    priceCents: "1900",
  },
  {
    id: "7",
    name: "John",
    image: "images/fanaanad/1 (1).jpg",
    color: "green",
    priceCents: "30000",
  },
  {
    id: "8",
    name: "John",
    image: "images/samsung/1 (10).jpg",
    color: "green",
    priceCents: "90000",
  },
  {
    id: "9",
    name: "John",
    image: "images/headPhones/1 (10).jpg",
    color: "green",
    priceCents: "70000",
  },
  {
    id: "10",
    name: "John",
    image: "images/airpots/1 (1).jpg",
    color: "green",
    priceCents: "2000",
  },
  {
    id: "11",
    name: "John",
    image: "images/laptop/1 (1).jpg",
    color: "green",
    priceCents: "1200",
  },
  {
    id: "12",
    name: "John",
    image: "images/shaatiyasha/1 (2).jpg",
    color: "green",
    priceCents: "2500",
  },
];
export let redmiProducts = [
  {
    id: "redmi1",
    image: "../images/redmi/1 (1).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi2",
    image: "../images/redmi/1 (2).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi3",
    image: "../images/redmi/1 (3).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi4",
    image: "../images/redmi/1 (4).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi5",
    image: "../images/redmi/1 (5).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi6",
    image: "../images/redmi/1 (6).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi7",
    image: "../images/redmi/1 (7).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi8",
    image: "../images/redmi/1 (8).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi9",
    image: "../images/redmi/1 (9).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi10",
    image: "../images/redmi/1 (10).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi11",
    image: "../images/redmi/1 (11).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi12",
    image: "../images/redmi/1 (12).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi13",
    image: "../images/redmi/1 (13).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi14",
    image: "../images/redmi/1 (14).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi15",
    image: "../images/redmi/1 (15).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi16",
    image: "../images/redmi/1 (16).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi17",
    image: "../images/redmi/1 (17).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi18",
    image: "../images/redmi/1 (19).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi19",
    image: "../images/redmi/1 (20).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
];

export let samsungProduct = [
  {
    id: "samsung1",
    image: "../images/samsung/1 (1).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung2",
    image: "../images/samsung/1 (2).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung3",
    image: "../images/samsung/1 (3).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung4",
    image: "../images/samsung/1 (4).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung5",
    image: "../images/samsung/1 (5).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung6",
    image: "../images/samsung/1 (6).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung7",
    image: "../images/samsung/1 (7).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung8",
    image: "../images/samsung/1 (8).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung9",
    image: "../images/samsung/1 (9).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung10",
    image: "../images/samsung/1 (10).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung11",
    image: "../images/samsung/1 (11).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung12",
    image: "../images/samsung/1 (12).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung13",
    image: "../images/samsung/1 (13).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung14",
    image: "../images/samsung/1 (14).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung15",
    image: "../images/samsung/1 (15).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung16",
    image: "../images/samsung/1 (16).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung17",
    image: "../images/samsung/1 (17).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung18",
    image: "../images/samsung/1 (19).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung19",
    image: "../images/samsung/1 (20).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung20",
    image: "../images/samsung/1 (21).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung21",
    image: "../images/samsung/1 (22).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung22",
    image: "../images/samsung/1 (23).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung23",
    image: "../images/samsung/1 (24).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung24",
    image: "../images/samsung/1 (25).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
];
export let samsungTabletProduct = [
  {
    id: "samsungTablet1",
    image: "../images/samsungtablet/1 (1).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet2",
    image: "../images/samsungtablet/1 (2).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet3",
    image: "../images/samsungtablet/1 (3).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet4",
    image: "../images/samsungtablet/1 (4).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet5",
    image: "../images/samsungtablet/1 (5).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet6",
    image: "../images/samsungtablet/1 (6).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet7",
    image: "../images/samsungtablet/1 (7).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet8",
    image: "../images/samsungtablet/1 (8).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet9",
    image: "../images/samsungtablet/1 (9).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet10",
    image: "../images/samsungtablet/1 (10).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet11",
    image: "../images/samsungtablet/1 (11).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet12",
    image: "../images/samsungtablet/1 (12).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet13",
    image: "../images/samsungtablet/1 (13).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet14",
    image: "../images/samsungtablet/1 (14).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet15",
    image: "../images/samsungtablet/1 (15).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet16",
    image: "../images/samsungtablet/1 (16).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet17",
    image: "../images/samsungtablet/1 (17).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet18",
    image: "../images/samsungtablet/1 (19).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet19",
    image: "../images/samsungtablet/1 (20).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet20",
    image: "../images/samsungtablet/1 (21).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet21",
    image: "../images/samsungtablet/1 (22).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet22",
    image: "../images/samsungtablet/1 (23).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsungTablet23",
    image: "../images/samsungtablet/1 (24).jpg",
    name: "Samsung Tablet ",
    color: "green",
    priceCents: "129900",
  },
];
export let shaatiProducts = [
  {
    id: "shaati1",
    image: "../images/shaatiyasha/1 (1).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati2",
    image: "../images/shaatiyasha/1 (2).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati3",
    image: "../images/shaatiyasha/1 (3).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati4",
    image: "../images/shaatiyasha/1 (4).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati5",
    image: "../images/shaatiyasha/1 (5).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati6",
    image: "../images/shaatiyasha/1 (6).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati7",
    image: "../images/shaatiyasha/1 (7).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati8",
    image: "../images/shaatiyasha/1 (8).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati9",
    image: "../images/shaatiyasha/1 (9).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati10",
    image: "../images/shaatiyasha/1 (10).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati11",
    image: "../images/shaatiyasha/1 (11).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati12",
    image: "../images/shaatiyasha/1 (12).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati13",
    image: "../images/shaatiyasha/1 (13).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati14",
    image: "../images/shaatiyasha/1 (14).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati15",
    image: "../images/shaatiyasha/1 (15).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati16",
    image: "../images/shaatiyasha/1 (16).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati17",
    image: "../images/shaatiyasha/1 (17).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati18",
    image: "../images/shaatiyasha/1 (19).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati19",
    image: "../images/shaatiyasha/1 (20).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati20",
    image: "../images/shaatiyasha/1 (21).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati21",
    image: "../images/shaatiyasha/1 (22).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati22",
    image: "../images/shaatiyasha/1 (23).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati23",
    image: "../images/shaatiyasha/1 (24).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati24",
    image: "../images/shaatiyasha/1 (25).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati25",
    image: "../images/shaatiyasha/1 (26).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati26",
    image: "../images/shaatiyasha/1 (27).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati27",
    image: "../images/shaatiyasha/1 (28).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati28",
    image: "../images/shaatiyasha/1 (29).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati29",
    image: "../images/shaatiyasha/1 (30).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati30",
    image: "../images/shaatiyasha/1 (31).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati31",
    image: "../images/shaatiyasha/1 (32).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati32",
    image: "../images/shaatiyasha/1 (33).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati33",
    image: "../images/shaatiyasha/1 (34).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati34",
    image: "../images/shaatiyasha/1 (35).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati35",
    image: "../images/shaatiyasha/1 (36).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shaati36",
    image: "../images/shaatiyasha/1 (3).jpg",
    name: "shaati",
    color: "green",
    priceCents: "129900",
  },
];

export let shortAirpodsProducts = [
  {
    id: "shortAirpods1",
    image: "../images/airpots/1 (1).jpg",
    name: "ShortAirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods2",
    image: "../images/airpots/1 (2).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods3",
    image: "../images/airpots/1 (3).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods4",
    image: "../images/airpots/1 (4).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods5",
    image: "../images/airpots/1 (5).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods6",
    image: "../images/airpots/1 (6).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods7",
    image: "../images/airpots/1 (7).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods8",
    image: "../images/airpots/1 (8).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods9",
    image: "../images/airpots/1 (9).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods10",
    image: "../images/airpots/1 (10).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods11",
    image: "../images/airpots/1 (11).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods12",
    image: "../images/airpots/1 (12).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods13",
    image: "../images/airpots/1 (13).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods14",
    image: "../images/airpots/1 (14).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (15).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (16).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (17).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (18).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "shortAirpods15",
    image: "../images/airpots/1 (19).jpg",
    name: "AirPods",
    color: "green",
    priceCents: "129900",
  },
];

export let tshirtPrdoct = [
  {
    id: "tShirt1",
    image: "../images/fanaanad/1 (1).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt2",
    image: "../images/fanaanad/1 (2).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt3",
    image: "../images/fanaanad/1 (3).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt4",
    image: "../images/fanaanad/1 (4).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt5",
    image: "../images/fanaanad/1 (5).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt6",
    image: "../images/fanaanad/1 (6).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt7",
    image: "../images/fanaanad/1 (7).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt8",
    image: "../images/fanaanad/1 (8).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt9",
    image: "../images/fanaanad/1 (9).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt10",
    image: "../images/fanaanad/1 (10).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt11",
    image: "../images/fanaanad/1 (11).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt12",
    image: "../images/fanaanad/1 (12).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt13",
    image: "../images/fanaanad/1 (13).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt14",
    image: "../images/fanaanad/1 (14).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt15",
    image: "../images/fanaanad/1 (15).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt16",
    image: "../images/fanaanad/1 (16).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt17",
    image: "../images/shaatiyasha/1 (17).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt18",
    image: "../images/shaatiyasha/1 (19).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt19",
    image: "../images/shaatiyasha/1 (20).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt20",
    image: "../images/shaatiyasha/1 (21).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt21",
    image: "../images/shaatiyasha/1 (22).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt22",
    image: "../images/shaatiyasha/1 (23).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt23",
    image: "../images/shaatiyasha/1 (24).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt24",
    image: "../images/shaatiyasha/1 (25).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt25",
    image: "../images/shaatiyasha/1 (26).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt26",
    image: "../images/shaatiyasha/1 (27).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt27",
    image: "../images/shaatiyasha/1 (28).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt28",
    image: "../images/shaatiyasha/1 (29).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt29",
    image: "../images/shaatiyasha/1 (30).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt30",
    image: "../images/shaatiyasha/1 (31).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt31",
    image: "../images/shaatiyasha/1 (32).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt32",
    image: "../images/shaatiyasha/1 (33).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt33",
    image: "../images/shaatiyasha/1 (34).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt34",
    image: "../images/shaatiyasha/1 (35).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tShirt35",
    image: "../images/shaatiyasha/1 (36).jpg",
    name: "T-Shirt",
    color: "green",
    priceCents: "129900",
  },
];

export let tabletProducts = [
  {
    id: "tablet1",
    image: "../images/tablet/1 (1).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet2",
    image: "../images/tablet/1 (2).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet3",
    image: "../images/tablet/1 (3).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet4",
    image: "../images/tablet/1 (4).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet5",
    image: "../images/tablet/1 (5).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet6",
    image: "../images/tablet/1 (6).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet7",
    image: "../images/tablet/1 (7).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet8",
    image: "../images/tablet/1 (8).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet9",
    image: "../images/tablet/1 (9).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet10",
    image: "../images/tablet/1 (10).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "tablet11",
    image: "../images/tablet/1 (11).jpg",
    name: "Tablet",
    color: "green",
    priceCents: "129900",
  },
];
export let vivoProducts = [
  {
    id: "1",
    image: "../images/vivo/1 (1).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2",
    image: "../images/vivo/1 (2).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "3",
    image: "../images/vivo/1 (3).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "4",
    image: "../images/vivo/1 (4).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "5",
    image: "../images/vivo/1 (5).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "6",
    image: "../images/vivo/1 (6).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "7",
    image: "../images/vivo/1 (7).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "8",
    image: "../images/vivo/1 (8).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "9",
    image: "../images/vivo/1 (9).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "10",
    image: "../images/vivo/1 (10).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "11",
    image: "../images/vivo/1 (11).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "12",
    image: "../images/vivo/1 (12).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "13",
    image: "../images/vivo/1 (13).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "14",
    image: "../images/vivo/1 (14).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "15",
    image: "../images/vivo/1 (15).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "16",
    image: "../images/vivo/1 (16).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "17",
    image: "../images/vivo/1 (17).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "18",
    image: "../images/vivo/1 (19).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "19",
    image: "../images/vivo/1 (20).jpg",
    name: "Vivo",
    color: "green",
    priceCents: "129900",
  },
];
