export let redmiProducts = [
  {
    id: "redmi1",
    image: "../images/redmi/1 (1).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi2",
    image: "../images/redmi/1 (2).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi3",
    image: "../images/redmi/1 (3).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi4",
    image: "../images/redmi/1 (4).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi5",
    image: "../images/redmi/1 (5).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi6",
    image: "../images/redmi/1 (6).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi7",
    image: "../images/redmi/1 (7).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi8",
    image: "../images/redmi/1 (8).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi9",
    image: "../images/redmi/1 (9).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi10",
    image: "../images/redmi/1 (10).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi11",
    image: "../images/redmi/1 (11).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi12",
    image: "../images/redmi/1 (12).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi13",
    image: "../images/redmi/1 (13).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi14",
    image: "../images/redmi/1 (14).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi15",
    image: "../images/redmi/1 (15).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi16",
    image: "../images/redmi/1 (16).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi17",
    image: "../images/redmi/1 (17).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi18",
    image: "../images/redmi/1 (19).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "redmi19",
    image: "../images/redmi/1 (20).jpg",
    name: "Redmi",
    color: "green",
    priceCents: "129900",
  },
];
