export let samsungTabletProduct = [
  {
    id: "1",
    image: "../images/samsungtablet/1 (1).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "2",
    image: "../images/samsungtablet/1 (2).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "3",
    image: "../images/samsungtablet/1 (3).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "4",
    image: "../images/samsungtablet/1 (4).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "5",
    image: "../images/samsungtablet/1 (5).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "6",
    image: "../images/samsungtablet/1 (6).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "7",
    image: "../images/samsungtablet/1 (7).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "8",
    image: "../images/samsungtablet/1 (8).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "9",
    image: "../images/samsungtablet/1 (9).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "10",
    image: "../images/samsungtablet/1 (10).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "11",
    image: "../images/samsungtablet/1 (11).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "12",
    image: "../images/samsungtablet/1 (12).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "13",
    image: "../images/samsungtablet/1 (13).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "14",
    image: "../images/samsungtablet/1 (14).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "15",
    image: "../images/samsungtablet/1 (15).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "16",
    image: "../images/samsungtablet/1 (16).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "17",
    image: "../images/samsungtablet/1 (17).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "18",
    image: "../images/samsungtablet/1 (19).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "19",
    image: "../images/samsungtablet/1 (20).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "20",
    image: "../images/samsungtablet/1 (21).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "21",
    image: "../images/samsungtablet/1 (22).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "22",
    image: "../images/samsungtablet/1 (23).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "23",
    image: "../images/samsungtablet/1 (24).jpg",
    name: "Iphone 15",
    color: "green",
    priceCents: "129900",
  },
];
