export let samsungProduct = [
  {
    id: "samsung1",
    image: "../images/samsung/1 (1).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung2",
    image: "../images/samsung/1 (2).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung3",
    image: "../images/samsung/1 (3).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung4",
    image: "../images/samsung/1 (4).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung5",
    image: "../images/samsung/1 (5).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung6",
    image: "../images/samsung/1 (6).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung7",
    image: "../images/samsung/1 (7).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung8",
    image: "../images/samsung/1 (8).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung9",
    image: "../images/samsung/1 (9).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung10",
    image: "../images/samsung/1 (10).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung11",
    image: "../images/samsung/1 (11).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung12",
    image: "../images/samsung/1 (12).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung13",
    image: "../images/samsung/1 (13).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung14",
    image: "../images/samsung/1 (14).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung15",
    image: "../images/samsung/1 (15).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung16",
    image: "../images/samsung/1 (16).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung17",
    image: "../images/samsung/1 (17).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung18",
    image: "../images/samsung/1 (19).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung19",
    image: "../images/samsung/1 (20).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung20",
    image: "../images/samsung/1 (21).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung21",
    image: "../images/samsung/1 (22).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung22",
    image: "../images/samsung/1 (23).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung23",
    image: "../images/samsung/1 (24).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
  {
    id: "samsung24",
    image: "../images/samsung/1 (25).jpg",
    name: "Samsung ",
    color: "green",
    priceCents: "129900",
  },
];
